### ISSUE TITLE
Add changelog to the project

### ISSUE THREAD

**Issue by alexkiro** [phihag/ipaddress#30]
It would be great if the project would have a changelog so we can easily figure out what changed in each version.

**Comment by phihag** [comment]
This project uses git, so you can always look in the [git history](https://github.com/phihag/ipaddress/commits/master) what happened. The advantage of that is that you can also see what exactly was changed. Since usually the release-to-release changes amount to *sync to upstream and fix one minor bug*, it's not like a summary in form of a changelog would make the list much more concise.

I also have no idea *why* you want to know what changed. If you don't trust me (or any other developer of the project), then you need to look in git anyways. If you do trust me, what possible reason could you have to use any but the latest version?

There will never be any backwards incompatibilities, and there will never be any new features except if the Python 3 ipaddress package introduces them. If you want to know changes to Python 3's ipaddress, follow [their changelog](https://docs.python.org/dev/whatsnew/changelog.html).

For these reasons, the best way to figure out what changed is to use:

Rough overview:
```
git log v1.0.17..v1.0.18 --oneline
```
Details:
```
git diff v1.0.17..v1.0.18
```
