### ISSUE TITLE
ip_network and '::/0'

### ISSUE THREAD

**Issue by github-abcde** [phihag/ipaddress#31]
Using Python 2.7.5, ipaddress-1.0.18-py2-none-any.whl
I'm encountering the following peculiarity when using `ip_network(data).version` to determine whether a netmask is IPv4 or IPv6:

```
Python 2.7.5 (default, Sep 15 2016, 22:37:39) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ipaddress;
>>> ipaddress.ip_network('::/0').version
4
>>> ipaddress.ip_network(u'::/0').version
6
```

Is this by design, or can this be fixed?

**Comment by phihag** [comment]
This is by design.

In Python 2, by default, `'::/0'` defines a string of bytes (not characters), more commonly written as `b'::/0'`. Therefore, your first line is equivalent to `ipaddress.ip_network(b'::/0').version`, or really `ipaddress.ip_network(b'\x3a\x3a\x2f\x30').version`.

You can construct an address from a binary packed representation. In this case, `b'::/0'` is the packed representation of the IPv4 address 58.58.47.48:

    >>> ipaddress.ip_address(u'58.58.47.48').packed
    b'::/0'

You can construct a network from the representation of one address. You will get a network which contains just this address. Therefore, `ipaddress.ip_network(b'::/0')` will give you the network 58.58.47.48/32.

One could decide that in the Python 2 backport, byte strings should be auto-converted to unicode strings. [Other backports have done that](https://github.com/phihag/ipaddress/blob/master/OTHER_BACKPORTS.md), but the consequences are quite horrifying, including making code intentionally incompatible between Python 2 and Python 3, but more seriously the same correct code behaving differently without any warning on Python 2 and Python 3.

The fix is any one of:

- Use Python 3, where this problem has been fixed
- Make sure to start all files with `from __future__ import unicode_literal` with (simple) static analysis.
- Make sure to always use explicit string literals (`b'foo'`, `u'foo'`, `r'foo'`) with static analysis.

In the last two points, string literals are of course only one example of where people mistakenly use byte strings or character strings when they ought to use the other. For full coverage, make sure to add plenty of assertions (like `assert isinstance(x, bytes)`) that ensure your code is correct in its use of string types.
