### ISSUE TITLE
IPv4Address improperly parses a 4 byte string as a valid IP address

### ISSUE THREAD

**Issue by zenzic64** [phihag/ipaddress#35]
I inadvertently stumbled on this when passing in an invalid IP to view the exception raised.  To my surprise, it returned the ascii values of the bytes as a valid IP address.  

>>> ipaddress.ip_address('blah')
IPv4Address(u'98.108.97.104')

**Comment by phihag** [comment]
This is correct behavior and documented in the [README](https://github.com/phihag/ipaddress/blob/master/README.md). If you forget `from __future__ import unicode_literals`, your code is equivalent to `ipaddress.ip_address(b'blah')`. `b'blah'` is the so-called [packed](https://docs.python.org/dev/library/ipaddress.html#ipaddress.IPv4Address.packed) representation of an IP address.

Under Python 3, `ipaddress.ip_address(b'blah') == ipaddress.IPv4Address(u'98.108.97.104')`. Since this backport aims to be compatible (no sense in writing *new* code that fails under Python 3), we are locked into this behavior.

If you want to create an ip_address from a human-readable representation instead from a byte string, pass in a character string instead of a byte string. For string literals, either put `from __future__ import unicode_literals` to the top of your file, or prefix character strings with `u`. For other inputs, [decode](https://docs.python.org/dev/library/stdtypes.html#bytes.decode) them from a byte string.
