### ISSUE TITLE
ip_network not working correctly

### ISSUE THREAD

**Issue by cjlallana** [phihag/ipaddress#53]
When checking an IP/network definition by using "ipaddress.ip_network", apparenty the function doesn't recognize IPs that don't have a standard 3 digit format. Examples:

Successful validation:
107.167.160.0/19
107.178.192.0/18
108.170.192.0/20
108.170.208.0/21

Error:
104.196.0.0/14
208.68.108.0/23
35.184.0.0/14
35.188.0.0/15

**Comment by phihag** [comment]
In future issues, here and otherwise, please include the error message you get. For more information on how to ask question (and issues, which are just a special case), review http://www.catb.org/~esr/faqs/smart-questions.html#intro and https://stackoverflow.com/help/how-to-ask .

Careful: ipaddress accepts both byte strings (for a binary representation of the address) as well as character strings. This behavior is intentionally unchanged in this backport to enable compatibility of your code with Python 3.3+'s built-in ipaddress module. For a more detailed discussion, see the [README](https://github.com/phihag/ipaddress/blob/master/README.md) and the [notes on other backports](https://github.com/phihag/ipaddress/blob/master/OTHER_BACKPORTS.md) (which I do not recommend, as this will break your code upon upgrading to Python 3.3+). 

This is reflected in the error message:

`>>> ipaddress.ip_network(b'104.196.0.0/14')`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`  File "ipaddress.py", line 201, in ip_network`
`    ' a unicode object?' % address)`
`ipaddress.AddressValueError: '104.196.0.0/14' does not appear to be an IPv4 or IPv6 network.` **`Did you pass in a bytes (str in Python 2) instead of a unicode object?`**

What other message would have led to you to the answer?

As written in the error message, the fix is simple: When dealing with characters, use characters strings (`unicode` objects in Python 2).
