### ISSUE TITLE
About to get dropped from gentoo portage because of python 2.7

### ISSUE THREAD

**Issue by ckonstanski** [phihag/ipaddress#57]
Today when running OS updates on gentoo hosts I was greeted with a warning that ipaddress will be dropped from the portage tree in 30 days.

https://packages.gentoo.org/packages/dev-python/ipaddress
https://bugs.gentoo.org/743724

I think this is because you're not keeping up with the ever-moving target of python versions. 2.7 and 3.6 are currently bad. Of these, 2.7 is a death sentence.

It would be nice if this important library didn't get pulled because of a lack of housekeeping. Can I help? I have a vested interest in keeping this package in gentoo. I'm not affiliated with the gentoo project. I'm just a programmer who needs this library for my job.

**Comment by ckonstanski** [comment]
Is ipaddress included python3.3+ ? Which is why the description of this git project says "older than 3.3". If so, this issue is a non-issue. Sorry for the spam.

**Comment by phihag** [comment]
@ckonstanski Correct, ipaddress is in the standard library on Python 3.3+; this is just a backport. Some users like to have the backport in 3.3 or 3.4, since it brings ipaddress features from later Python versions. However, that's certainly not the gentoo way; if you're using 3.8, there is no possible use for this backport.
